name: AWS

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" 

      - name: Install dependencies
        run: npm ci

      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.AWS_HOST_IP }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AAWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/hackathon
            sudo git pull
            sudo npm install # Changed to "npm install" instead of "npm i"
            sudo pm2 restart

