name: AWS

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          password: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            whoami
            cd /home/ubuntu/backend
            sudo git pull
            sudo npm install 
            sudo pm2 restart
